{{- if .Values.celeryWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snapper.fullname" . }}-celery-worker
  labels:
    {{- include "snapper.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-worker
spec:
  replicas: {{ .Values.celeryWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "snapper.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "snapper.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "snapper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: celery-worker
          image: {{ include "snapper.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery", "-A", "app.celery_app", "worker", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: {{ include "snapper.fullname" . }}-config
            - secretRef:
                name: {{ include "snapper.secretName" . }}
          resources:
            {{- toYaml .Values.celeryWorker.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
